version: "3.9"
services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recs
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recs"]
      interval: 5s
      timeout: 5s
      retries: 12

  api:
    build: ./backend
    env_file: backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app

  web:
    image: node:20-alpine
    working_dir: /usr/src/app
    command: sh -c "npm i -g vite && mkdir -p /usr/src/app && npx --yes create-vite@latest frontend -- --template react-ts || true && cd frontend && npm i && npm run dev -- --host 0.0.0.0 --port 5173"
    ports: ["5173:5173"]
    volumes:
      - ./frontend:/usr/src/app/frontend
    depends_on: [api]
